Tracker:AddLocations("locations/central_bunker/lockers.json")
Tracker:AddLocations("locations/central_bunker/generator_room.json")
Tracker:AddLocations("locations/central_bunker/dog_tag_batiste.json")
Tracker:AddLocations("locations/central_bunker/gun.json")
Tracker:AddLocations("locations/central_bunker/medical_storage.json")
Tracker:AddLocations("locations/central_bunker/photo_doctor.json")
Tracker:AddLocations("locations/central_bunker/arena.json")

Tracker:AddLocations("locations/officer_quarters/delisles_room.json")
Tracker:AddLocations("locations/officer_quarters/dog_tag_wine_cellar.json")
Tracker:AddLocations("locations/officer_quarters/photo_fournier.json")
Tracker:AddLocations("locations/officer_quarters/photo_joubert.json")
Tracker:AddLocations("locations/officer_quarters/photo_strategic.json")

Tracker:AddLocations("locations/prison/photo_warden.json")
Tracker:AddLocations("locations/prison/map_prison.json")
Tracker:AddLocations("locations/prison/cutters.json")
Tracker:AddLocations("locations/prison/milliardtag.json")

Tracker:AddLocations("locations/maintenance/photo_foremans.json")
Tracker:AddLocations("locations/maintenance/clerks_office_maintenance.json")
Tracker:AddLocations("locations/maintenance/chapel.json")
Tracker:AddLocations("locations/maintenance/tunnel.json")
Tracker:AddLocations("locations/maintenance/pillbox.json")
Tracker:AddLocations("locations/maintenance/changing_room.json")
Tracker:AddLocations("locations/maintenance/break_room.json")
Tracker:AddLocations("locations/maintenance/outside_hallway.json")

Tracker:AddLocations("locations/arsenal/munitions_storage.json")
Tracker:AddLocations("locations/arsenal/storage_area_a.json")
Tracker:AddLocations("locations/arsenal/explosives_storage.json")
Tracker:AddLocations("locations/arsenal/clerks_office_arsenal.json")

Tracker:AddLocations("locations/soldier_quarters/barracks.json")
Tracker:AddLocations("locations/soldier_quarters/hallway.json")
Tracker:AddLocations("locations/soldier_quarters/darkroom.json")
Tracker:AddLocations("locations/soldier_quarters/clerks_office_sq.json")
Tracker:AddLocations("locations/soldier_quarters/mess_hall.json")
Tracker:AddLocations("locations/soldier_quarters/arsenal_code.json")

Tracker:AddLocations("locations/roman_tunnels/crater.json")
Tracker:AddLocations("locations/roman_tunnels/detonator_handle.json")
Tracker:AddLocations("locations/roman_tunnels/fog.json")
Tracker:AddLocations("locations/roman_tunnels/save_room.json")